# Generated by Django 4.2 on 2023-05-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_cruddb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrudAppDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=55)),
            ],
        ),
    ]
