# Generated by Django 4.2 on 2023-05-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrudAppDB',
        ),
    ]
